name: Optimize
on:
  push:

jobs:
  svgs:
    if: "contains(github.event.head_commit.message, 'autoupdate')" # only run after docs update
    name: Optimize SVGs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ericcornelissen/svgo-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
